; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_ldf_mode = deep+
monitor_port = 9600
build_src_filter = +<test.cpp>;
lib_deps = 
	arduino-libraries/Servo @ ^1.2.1
	emelianov/modbus-esp8266@^4.1.0
	luisllamasbinaburo/I2CScanner@^1.0.1
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	adafruit/DHT sensor library@^1.4.7
	adafruit/Adafruit Unified Sensor@^1.1.15
	jfturcot/SimpleTimer@0.0.0-alpha+sha.b30890b8f7
